steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args:
    [
      'build',
      'europe-west1-docker.pkg.dev/dev-michal-cupper/cloud-run-source-deploy/enhanced_description-function:${SHORT_SHA}',
      '--builder', 'europe-west1-docker.pkg.dev/serverless-runtimes/google-22-full/builder/python:python_20250914_RC00',
      '--env', 'GOOGLE_RUNTIME_VERSION=3.13.7',
      '--env', 'GOOGLE_FUNCTION_TARGET=enrich_description',
      '--env', 'FUNCTION_SIGNATURE_TYPE=http',
      '--path', './workspace',
      '--publish' #
    ]
  id: 'Build and Push Image with Buildpacks'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [
    'functions', 'deploy', 'enhanced_description',
          '--region', 'europe-west1',
          '--gen2',
          '--runtime', 'python313',
          '--memory', '512Mi',
          '--max-instances', '1',
          '--trigger-http',
          '--service-account', 'cloud-run@dev-michal-cupper.iam.gserviceaccount.com',
          '--image',
          'europe-west1-docker.pkg.dev/dev-michal-cupper/cloud-run-source-deploy/enhanced-description-function:${SHORT_SHA}'
    ]
  id: 'Deploy Cloud Function on Cloud Run'

serviceAccount: 'projects/dev-michal-cupper/serviceAccounts/cloud-run@dev-michal-cupper.iam.gserviceaccount.com'

logsBucket: 'gs://enriched_description'

options:
  logging: GCS_ONLY