steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args:
    [
      'build',
      'europe-west1-docker.pkg.dev/dev-michal-cupper/cloud-run/gemini-enhanced-description:${SHORT_SHA}',
      '--builder', 'europe-west1-docker.pkg.dev/serverless-runtimes/google-22-full/builder/python:python_20250914_RC00',
      '--env', 'GOOGLE_RUNTIME_VERSION=3.13.7',
      '--env', 'GOOGLE_FUNCTION_TARGET=enrich_description',
      '--env', 'FUNCTION_SIGNATURE_TYPE=http',
      '--path', '.',
      '--publish'
    ]
  id: 'Build and Push Image with Buildpacks'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [
      'run', 'deploy', 'gemini-enhanced-description',
      '--image', 'europe-west1-docker.pkg.dev/dev-michal-cupper/cloud-run/gemini-enhanced-description:${SHORT_SHA}',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--no-allow-unauthenticated',
      '--set-secrets', 'api_key=api_key:latest',
      '--service-account', 'cloud-run@dev-michal-cupper.iam.gserviceaccount.com',
      '--memory', '512Mi'
    ]
  id: 'Deploy Cloud Function on Cloud Run'

serviceAccount: 'projects/dev-michal-cupper/serviceAccounts/cloud-run@dev-michal-cupper.iam.gserviceaccount.com'
logsBucket: 'gs://gemini-enhanced-description'
options:
  logging: GCS_ONLY