steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - enhanced-description
  - --region=europe-west1
  - --source=.
  - --runtime=python313
  - --gen2
  - --trigger-http
  - --memory=512Mi
  - --max-instances=1
  - --service-account=cloud-run@dev-michal-cupper.iam.gserviceaccount.com
  id: 'Deploy Cloud Function from source'

timeout: 1200s
serviceAccount: 'projects/dev-michal-cupper/serviceAccounts/cloud-run@dev-michal-cupper.iam.gserviceaccount.com'
logsBucket: 'gs://enriched_description'
options:
  logging: GCS_ONLY